name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
      - '!*dev*'
      - '!*pre*'
      - '!*post*'
  pull_request:
  workflow_dispatch:
  schedule:
    #        ┌───────── minute (0 - 59)
    #        │ ┌───────── hour (0 - 23)
    #        │ │ ┌───────── day of the month (1 - 31)
    #        │ │ │ ┌───────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────── day of the week (0 - 6 or SUN-SAT)
    - cron: '0 7 * * *'  # Every day at 07:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Core tests to run on PRs and pushes
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: py310
        - macos: py39
        - windows: py38
        # TODO: enable codestyle (i.e. flake8) when PEP8 issues are fixed
        #- linux: codestyle
      coverage: codecov

  # More detailed tests which only run when scheduled, or manually triggered from the Actions tab
  cron:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    with:
      envs: |
        - linux: py38
        - linux: py39
        - macos: py38
        - macos: py310
        - windows: py310
        # Test that the latest commit to key deps don't break this package
        - linux: py310-dev
        # Test that the docs can build without any warnings or errors
        - linux: build_docs
      coverage: codecov

  # Builds surveySimPP into a package suitable for upload to PyPI
  # and verifies that the tests pass before uploading (if configured)
  build:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    needs: [tests]
    with:
      test_extras: test
      test_command: pytest -p no:warnings --pyargs surveySimPP
      upload_to_pypi: false
#    secrets:
#      pypi_token: ${{ secrets.pypi_token }}
# When you're ready to upload to PyPI, remove the `upload_to_pypi` line
# (default is to upload tags which begin with "v"), and add your PyPI
# token to the repository secrets and uncomment the two lines above.
